### `numpy`



### What is numpy?

- The `NumPy` is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, and various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


- At the core of the `NumPy` package, is the `ndarray` object. 
- This encapsulates n-dimensional arrays of homogeneous data types.

### Numpy Arrays Vs Python Sequences

- `NumPy` arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a `NumPy` array are all required to be of the same data type, and thus will be the same size in memory.

- `NumPy` arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using `NumPy` arrays; though these typically support Python-sequence input, they convert such input to `NumPy` arrays prior to processing, and they often output `NumPy` arrays.

### Creating Numpy Arrays

- To create numpy array we need to use `np.array()`
- In this function we need to provide a list.
- We can call the 1d array as **Vectors** and 2d as **Matrix** and 3d arrays as **Tensors**.
- We can also create arrays of our required datatypes by using the `dtype` parameter.
- Using `np.arrange()` almost work as `range()`. Here also we need to provide start, stop and stride.
- The `reshape()` is to transform the shape of the array.
- `np.ones` create an array where we need to provide a tuple for shape and it will create a numpy array where each item will be `1`. Same can be done for arrays of `0` using `np.zeros`.
- `np.random` is to create a numpy array of random numbers between `0` and `1`. Here also we need to provide the shape as a tuple.
- `np.linspace` stands for **Linear Space**. Here we need to provide a range and number of items. It creates points at equal distance in a linearly seperable way for a given range. Here we can also provide the `dtype` for datatype.
> `np.linspace(lower_range, upper_range, number_of_items)`
- `np.identity` is to create identity matrix. The identity matrix is a matrix where the diagonal items are `1` and rest is `0`.
- **Whenever we create arrays in numpy by default they are of `float` datatype**.

In [1]:
# importing the library
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
# 2D arrays

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3D arrays

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# Creating array of float datatype using `dtype`

n = np.array([1,2,3], dtype=float)
print(n)

[1. 2. 3.]


In [5]:
# Creating array from 1 to 10 for every alternate number

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
# reshape
# Creating a 5X2 shape matrix

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
# initially it is a 1d array
a = np.arange(1,11)
print(a)
print("The dimension of the array is: ", a.ndim)
print("\n")

# Now transforming it to a 2d array using reshape()
a = a.reshape(5,2)
print(a)
print("The dimension of the array is: ", a.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
The dimension of the array is:  1


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
The dimension of the array is:  2


In [10]:
# Creating a 4d array 
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [11]:
# np.ones

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
# np.zeros

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# np.random
# Here we need to call the random() after np.random

np.random.random((3,4))

array([[0.2948992 , 0.98945129, 0.13479974, 0.02664977],
       [0.53495087, 0.91921918, 0.79281846, 0.11358034],
       [0.09564821, 0.15976966, 0.83077326, 0.16947422]])

In [14]:
# np.linspace
# Here we are creating an array of 10 items between -10 and 10

np.linspace(-10,10,10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [15]:
# np.identity
# Creating a 3X3 identity matrix.

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

- We can see the dimension of the array using the `ndim`.
- The `shape` tells how many items are there in each dimension.
- The `size` tells number of items in that array.
- The `itemsize` tells how much memory space occupied by each item.
- The `dtype` is to know the datatype of the items of the array.

In [16]:
# Creating a 1d array (vector) upto 10 using integer datatype

a1 = np.arange(10,dtype=np.int32)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Creating a 2d array (matrix) upto 12 using float datatype and of 3X4 dimension

a2 = np.arange(12,dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [18]:
# Creating a 3d array (tensor) upto 8 of 3X3 dimension
# Here the index is (z,x,y)

a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
# ndim to get the number of dimension

print("The dimension of the a1 array is: ", a1.ndim)
print("The dimension of the a2 array is: ", a2.ndim)
print("The dimension of the a3 array is: ", a3.ndim)

The dimension of the a1 array is:  1
The dimension of the a2 array is:  2
The dimension of the a3 array is:  3


In [20]:
# shape
print(a1)
print("The Shape of the a1 array is: ", a1.shape)
print("*"*50)
print(a2)
print("The Shape of the a2 array is: ", a2.shape)
print("*"*50)
print(a3)
print("The Shape of the a3 array is: ", a3.shape)

[0 1 2 3 4 5 6 7 8 9]
The Shape of the a1 array is:  (10,)
**************************************************
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
The Shape of the a2 array is:  (3, 4)
**************************************************
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
The Shape of the a3 array is:  (2, 2, 2)


In [22]:
# size

print(a1)
print("The number of items in a1 array is: ", a1.size)
print("*"*50)
print(a2)
print("The number of items in a2 array is: ", a2.size)
print("*"*50)
print(a3)
print("The number of items in a3 array is: ", a3.size)

[0 1 2 3 4 5 6 7 8 9]
The number of items in a1 array is:  10
**************************************************
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
The number of items in a2 array is:  12
**************************************************
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
The number of items in a3 array is:  8


In [24]:
# itemsize

print("The memory space occupied by a1 array is: ", a1.itemsize, "bytes")
print("The memory space occupied by a2 array is: ", a2.itemsize, "bytes")
print("The memory space occupied by a3 array is: ", a3.itemsize, "bytes")

The memory space occupied by a1 array is:  4 bytes
The memory space occupied by a2 array is:  8 bytes
The memory space occupied by a3 array is:  4 bytes


In [25]:
# dtype
print("The datatype of a1 array is: ",a1.dtype)
print("The datatype of a2 array is: ",a2.dtype)
print("The datatype of a3 array is: ",a3.dtype)

The datatype of a1 array is:  int32
The datatype of a2 array is:  float64
The datatype of a3 array is:  int32


### Changing Datatype

- Using `astype()` we can change the datatype of the items of the array.
- The change is temporary so we need to put it in a variable for future use.

In [29]:
# astype

print("The present datatype of a3 array is: ",a3.dtype)

# Now changing the datatype to float
a3 = a3.astype(np.float32)

print(a3)

print("The changed datatype of a3 array is: ",a3.dtype)

The present datatype of a3 array is:  int64
[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
The changed datatype of a3 array is:  float32


### Array Operations

- We can perform scaler, relational and vector operations on arrays.
- In Scaler operation we operate with a scaler (a single number) upon a single numpy array.
- In Vector operation we operate with two numpy arrays. Here remember the shape of both the arrays must be same.

In [30]:
# Creating an array of 3X4 ranged from 0 to 11

a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
# Creating an array of 3X4 ranged from 12 to 24

a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
# scalar operations
# Here we will make square of each items of the a1 array

print("The original array is:")
print(a1)
# performing scalar arithmetic to get the square
print("After change the array is:")
print(a1 ** 2)

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After change the array is:
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [33]:
# relational
# Here it performs itemwise comparison

# Which item is equal to value of 15
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
# vector operations
# arithmetic operation of addition of both the arrays
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Functions

- `np.round()` rounds an array to the given number of decimals.
- `np.max()` to get the maximum item.
- `np.min()` to get the minimum item.
- `np.sum()` to get the sum of all the items.
- `np.prod()` to get the product of all the items.
- We can use the `axis` parameter to perform the above functions upon items of a row or column. `0` is for columns and `1` is for rows.
- The `np.dot()` is used to find the dot product between two matrices. The condition for dot product is that the column number of first matrix should be equal to the row number of the second matrix.
- `np.log()` to get the log value of all the items of the array.
- `np.exp()` to get the exponent value of all the items of the array.
- `np.round()` to get the rounded value of nearest integer.
- `np.floor()` to get the nearest lower value integer.
- `np.ceil()` to get the nearest upper value integer.

**Statistical Functions:**
- The `mean()`, `median()`, `std()` and `var()` is to find the Mean, Median, Standard Deviation and Variance of the array. Here also we can perform the task columnwise or rowwise using the `axis` parameter.

**Trigonometric Functions:**
- Here we can use the `sin()`, `cos()`, `tan()` etc. These are never used in data science.

In [35]:
# Creating a 3X3 matrix with random values 

a1 = np.random.random((3,3))
print(a1)

[[0.03982893 0.97750614 0.80385849]
 [0.73095082 0.62936663 0.66312124]
 [0.38591163 0.4345653  0.04679368]]


In [36]:
# np.round

a1 = np.round(a1*100)
print(a1)

[[ 4. 98. 80.]
 [73. 63. 66.]
 [39. 43.  5.]]


In [37]:
# max()

np.max(a1)

98.0

In [38]:
# min()

np.min(a1)

4.0

In [39]:
# sum()

np.sum(a1)

471.0

In [40]:
# prod()

np.prod(a1)

79815358022400.0

In [41]:
# Getting maximum item of each row

np.max(a1, axis=1)

array([98., 73., 43.])

In [42]:
# Getting minimum item of each column

np.min(a1, axis=0)

array([ 4., 43.,  5.])

In [ ]:
# mean
np.mean(a1, axis=1)

array([317.55555556, 854.        ,  96.22222222])

In [43]:
# median

np.median(a1, axis=0)

array([39., 63., 66.])

In [44]:
# std

np.std(a1, axis=1)

array([40.73764298,  4.18993503, 17.04894914])

In [45]:
# var

np.var(a1, axis=0)

array([ 793.55555556,  516.66666667, 1060.22222222])

In [46]:
# sin() for all the items
np.sin(a1)

array([[-0.7568025 , -0.57338187, -0.99388865],
       [-0.67677196,  0.1673557 , -0.02655115],
       [ 0.96379539, -0.83177474, -0.95892427]])

#### `dot product`

In [47]:

a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a3 = np.arange(12,24).reshape(4,3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [49]:
print("The shape of a2 matrix is: ", a2.shape)
print("The shape of a3 matrix is: ", a3.shape)

The shape of a2 matrix is:  (3, 4)
The shape of a3 matrix is:  (4, 3)


In [50]:
# So as the column i.e 4 of first matrix is equal to row of second matrix
# So dot product is

a4 = np.dot(a2,a3)
print(a4)
print("The shape of a4 matrix is: ", a4.shape)

[[114 120 126]
 [378 400 422]
 [642 680 718]]
The shape of a4 matrix is:  (3, 3)


In [51]:
# log() 

np.log(a1)

array([[1.38629436, 4.58496748, 4.38202663],
       [4.29045944, 4.14313473, 4.18965474],
       [3.66356165, 3.76120012, 1.60943791]])

In [52]:
# exponents()

np.exp(a1)

array([[5.45981500e+01, 3.63797095e+42, 5.54062238e+34],
       [5.05239363e+31, 2.29378316e+27, 4.60718663e+28],
       [8.65934004e+16, 4.72783947e+18, 1.48413159e+02]])

In [54]:
# Getting 2X3 matrix of random numbers between 1 to 100

a = np.random.random((2,3))*100
a

array([[30.38833007, 60.34659647, 99.6583956 ],
       [26.35402373, 94.86244157,  7.72814386]])

In [55]:
# round()

np.round(a)

array([[ 30.,  60., 100.],
       [ 26.,  95.,   8.]])

In [57]:
a = np.random.random((2,3))*100
a

array([[41.92582425, 78.62857186, 45.55104414],
       [75.01299899, 28.34586224, 65.71955176]])

In [58]:
# floor

np.floor(a)

array([[41., 78., 45.],
       [75., 28., 65.]])

In [59]:
a = np.random.random((2,3))*100
a

array([[25.8704394 , 22.17157305, 39.71231832],
       [51.75877441, 99.20562982, 48.63290731]])

In [60]:
# ceil

np.ceil(a)

array([[ 26.,  23.,  40.],
       [ 52., 100.,  49.]])

### Indexing and Slicing

- `array[row_num, col_num]` for indexing of 2d arrays.
- `array[array_num, row_num, col_num]` for indexing of 3d arrays.
- Slicing concept is same as python. With the help of slicing we can fetch multiple items at one go.
- Here we provide the starting and ending points for row number and column number seperated with `:` in case of 2d and 3d array.
- For 2d array:
> `array[row_start:row_end:stride, col_start:col_end:stride]`
- For 3d array:
> `array[array_start:array_end:stride, row_start:row_end:stride, col_start:col_end:stride]`

In [61]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
# Getting the last item of a1 array

a1[-1]

9

In [ ]:
# Getting the item from 2nd row 1st colum of the a2 array

a2[1,0]

4

In [65]:
# Find 6 from a2 array

a2[1,2]

6

In [66]:
# Here we are finding 6 from 3d array a3

a3[1,1,0]

6

In [67]:
# Getting 5 from a3

a3[1,0,1]

5

In [69]:
# Getting 0 from a3

a3[0,0,0]

0

#### `slicing`

In [70]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
# getting 2,3,4 from a1

a1[2:5]

array([2, 3, 4])

In [72]:
# getting 2,4 from a1

a1[2:5:2]

array([2, 4])

In [73]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
# getting 5,6,9,10 

a2[1: ,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [75]:
# getting 0,3,8,11

a2[::2 , ::3]

array([[ 0,  3],
       [ 8, 11]])

In [78]:
# getting 1,3,9,11

a2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [79]:
# getting 4,7

a2[1, ::3]

array([4, 7])

In [81]:
# getting 1,2,3,5,6,7

a2[0:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [82]:
# getting 1,3,5,7

a2[0:2, 1::2]

array([[1, 3],
       [5, 7]])

In [83]:
# Now for 3d

# Creating a 3d array of 3X3X3
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [86]:
# Getting the middle 2d array

a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [87]:
# Getting without the middle 2d array

a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [91]:
# Getting the 2nd row of the 1st 2d array i.e. 3,4,5

a3[0, 1, :]

array([3, 4, 5])

In [92]:
# Getting the middle column of the 2nd numpy array

a3[1, 0:, 1]

array([10, 13, 16])

In [93]:
# Getting 22,23,25,26

a3[2, 1:, 1:]

array([[22, 23],
       [25, 26]])

In [95]:
# Getting 0,2,18,20

a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

- We can run loop over the numpy array.
- In case of 2d array it prints 1 row at a time and for the 3d array it prints 1 array at a time.
- The `np.nditer()` is use to print 1 item at a time when printing a multidimensional array.

In [96]:
a1

for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [97]:
# In case of 2 d array
# Here one row gets printed at a time

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [101]:
# In case of 2 d array
# Here one 2d array gets printed at a time

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [103]:
# printing individual item of the 2d array
# using "np.nditer()"

for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [104]:
# printing individual item of the 3d array

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping and Transpose

- `np.reshape()` to reshape the array.
- `np.transpose()` to transpose a matrix. i.e. row and columns get interchanged. We can also do this by `array.T`
- `np.ravel()` can convert any dimensional array to 1d.
- These changes are all temporary.

In [105]:
# Original a2

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
# after Transpose

np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [108]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [110]:
# ravel

print("Dimension of a3: ", a3.ndim)
a3 = a3.ravel()
print("Now Dimension of a3: ", a3.ndim)
print(a3)

Dimension of a3:  3
Now Dimension of a3:  1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


### Stacking

- `np.hstack()` to stack them horizontally. The arrays to be passed in form of tuple. Same to do vertically using `np.vstack()`
- Remember the shape of the arrays should be same to be get stacked.

> `np.hstack((array_1, array_2,...,array_n))`

> `np.vstack((array_1, array_2,...,array_n))`

In [111]:
a4 = np.arange(12).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [113]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [114]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

- `np.hplit(array, num_of_split)` to do Horizontal split. And `np.vsplit()` to split vertically.

In [115]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
# Horizontal split
# Splitting the a4 array in 2 equal parts horizontally

try:
    h1,h2 = np.hsplit(a4,2)
    print(h1)
    print("\n")
    print(h2)
except Exception as err:
    print(f"The error type is: '{type(err).__name__}' and the error is: {err.args}.")

[[0 1]
 [4 5]
 [8 9]]


[[ 2  3]
 [ 6  7]
 [10 11]]


In [116]:
# If we try to split in unequal splits we get error

try:
    np.hsplit(a4,5)
except Exception as err:
    print(f"The error type is: '{type(err).__name__}' and the error is: {err.args}.")

The error type is: 'ValueError' and the error is: ('array split does not result in an equal division',).


In [117]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [126]:
# Vertical split
# Splitting the a5 array in 3 equal parts vertically

try:
    v1,v2,v3 = np.vsplit(a5,3)
    print(v1)
    print("\n")
    print(v2)
    print("\n")
    print(v3)
except Exception as err:
    print(f"The error type is: '{type(err).__name__}' and the error is: {err.args}.")

[[12 13 14 15]]


[[16 17 18 19]]


[[20 21 22 23]]


In [127]:
# For unequal vertical split

try:
    np.vsplit(a5,2)
except Exception as err:
    print(f"The error type is: '{type(err).__name__}' and the error is: {err.args}.")

The error type is: 'ValueError' and the error is: ('array split does not result in an equal division',).
