### Here we will test the model with new user input data

In [1]:
import pickle
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
# loading the models

ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/titanic_clf.pkl','rb'))

In [3]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
# Here we are using data of the passenger index 331

test_input = np.array([1, 'male', 45.5, 0, 0, 28.5, 'S'], dtype=object).reshape(1,7)

In [4]:
# Checking the input

test_input

array([[1, 'male', 45.5, 0, 0, 28.5, 'S']], dtype=object)

In [5]:
# doing the transformations

test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1, 1))
test_input_sex

array([[0., 1.]])

In [6]:
test_input_embarked = ohe_embarked.transform(test_input[:, -1].reshape(1,1))
test_input_embarked

array([[0., 0., 1.]])

In [7]:
test_input_age = test_input[:,2].reshape(1,1)
test_input_age

array([[45.5]], dtype=object)

In [8]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],
                                         test_input_age,test_input_sex,
                                         test_input_embarked),axis=1)
test_input_transformed.shape

(1, 10)

In [9]:
# Doing prediction

clf.predict(test_input_transformed)

array([0], dtype=int64)

**Notes:**

- So if we don't use ***Pipelines*** then we need to write same series of steps twice once when creating the model and again when we get user input data to feed the model.