## *Deep Learning*


- **Reasons behind the popularity of *Deep Learning*:**
  - **Growth in Data in recent years:** 
    - In recent years the volume of data generated by different businesses is huge compare to few years back. Also due to growth of social media the data generation grow exponencially. Now ***Deep Learning*** works better if the volume of data is higher.   
  - **Advancement in Hardware:**
    - With advanced hardwares in computers as specialized hardwares like ***GPU (Graphical Processing Unit)*** and ***TPU (Tensorflow Processing Unit)*** the works of ***Deep Learning*** becomes faster and easier now a days.    
  - **Python and Opensource Ecosystem:**
    - Now a days with the programming language like ***Python*** the ***Deep Learning*** programs can be written even without programming knowledge, it was not possible previously as earlier the programs are written in ***C++*** and ***JAVA*** which needed proper programming skills. Also ***Deep Learning*** Frameworks like ***Pytorch*** and ***Tensorflow*** makes the job easier.    
  - **Cloud and AI:**
    - Now a days we can run the program even in Clouds (renting a computer) without having a high end machine.

### Installing *Tensorflow2.0* 

- To install tensorflow

**pip install tensorflow==2.2.0**

In [2]:
# to check whether we have tensorflow

import tensorflow as tf

In [3]:
tf.__version__

'2.11.0'

#### `Matrix Multiplication`

In [1]:
import numpy as np

In [2]:
# Creating two multi-dimensional arrays

revenue = np.array([[180,200,220], [24,36,40], [12,18,20]])
expenses = np.array([[80,90,100], [10,16,20], [8,10,10]])

In [3]:
# Checking the matrixes

revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [4]:
expenses

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

In [5]:
# Now calculating profits by simple subtraction of the two matrixes

profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [6]:
# Again creating matrixes for multiplication

price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50], [5,10,15], [2,5,7]])

In [7]:
price_per_unit

array([1000,  400, 1200])

In [8]:
units

array([[30, 40, 50],
       [ 5, 10, 15],
       [ 2,  5,  7]])

In [9]:
# now doing multiplication

price = price_per_unit*units
price

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [10]:
# We can also do dot product using "dot()" of numpy

np.dot(price_per_unit, units)

array([34400, 50000, 64400])